name: Deploy PR Preview

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r doc_req.txt

    - name: Configure Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Deploy dev version using mike
      if: github.ref == 'refs/heads/main'
      run: mike deploy dev --update-aliases --push

    - name: Deploy release version using mike
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
          version=${GITHUB_REF##*/}
          echo "Deploying release version $version"
          mike deploy "$version" latest --update-aliases --push
