name: Deploy PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r doc_req.txt

    - name: Configure Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Deploy PR version using mike
      env:
        PR: pr-${{ github.event.number }}
      run: |
        git fetch origin gh-pages --depth=1
        git checkout gh-pages || git checkout --orphan gh-pages
        mike deploy $PR --update-aliases
        git push origin gh-pages

    - name: Comment preview URL on PR
      uses: actions/github-script@v7
      with:
        script: |
          const pr = context.payload.pull_request.number;
          const repo = context.repo.repo;
          const owner = context.repo.owner;
          const url = `https://${owner}.github.io/${repo}/pr-${pr}/`;
          github.rest.issues.createComment({
            issue_number: pr,
            owner,
            repo,
            body: `📘 Preview available: [View Docs Preview](${url})`
          });
